/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Card from "../../components/Card";
import { useRouter } from "next/router";
import PostCard from "components/PostCard";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex mt-2 max-w-4xl mx-auto gap-6 p-4 sm:p-2">
          <div className="w-1/3 hidden sm:block">
            <Card noPadding={false}>Test Links</Card>
          </div>

          <div className="grow">
            <Card noPadding={true}>
              <div className="flex-1 px-4 py-5 sm:p-6 flex space-x-4 items-center">
                <a
                  className="cursor-pointer transition duration-100 ease-in-out flex-shrink-0 hover:opacity-90 h-12 w-12 rounded-full overflow-hidden"
                  href="/member/GOozf2Ub6G"
                >
                  <img
                    src="https://plus.unsplash.com/premium_photo-1664203067979-47448934fd97?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
                    alt=""
                    className=""
                  />
                </a>
                <button
                  type="button"
                  className="bg-gray-200 border border-none flex focus-visible:ring focus:outline-none  hover:bg-gray-300 items-center px-3 py-2 rounded-md w-full"
                  onClick={() => router.push("/submit")}
                >
                  <span className="flex">
                    <span className="inline-flex items-center">
                      What’s on your mind?
                    </span>
                  </span>
                </button>
              </div>
            </Card>

            {/* <Card noPadding={false}>

            </Card> */}
            <PostCard />
          </div>
        </div>
      </main>
    </>
  );
}
